apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: ${WORKSHOP_NAMESPACE}
  labels:
    app: keycloak
    app.kubernetes.io/part-of: people-service
type: Opaque
stringData:
  KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
  KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
