apiVersion: v1
kind: Secret
metadata:
  name: people-backend-notifications
  namespace: ${WORKSHOP_NAMESPACE}
  labels:
    app.kubernetes.io/part-of: people-service
type: Opaque
stringData:
  DEVELOPER_HUB_NOTIFICATIONS_TOKEN: "${PEOPLE_NOTIFICATION_TOKEN}"
