apiVersion: v1
kind: Secret
metadata:
  name: people-postgres
  namespace: ${WORKSHOP_NAMESPACE}
  labels:
    app: people-postgres
    app.kubernetes.io/part-of: people-service
type: Opaque
stringData:
  POSTGRES_DB: ${PEOPLE_DB_NAME}
  POSTGRES_USER: ${PEOPLE_DB_USER}
  POSTGRES_PASSWORD: ${PEOPLE_DB_PASSWORD}
