apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-secrets
  namespace: ${RHDH_NAMESPACE}
  labels:
    app.kubernetes.io/part-of: developer-hub
type: Opaque
stringData:
  ENABLE_VLLM: ""
  ENABLE_VERTEX_AI: ""
  ENABLE_OPENAI: "${LIGHTSPEED_ENABLE_OPENAI}"
  ENABLE_OLLAMA: ""
  VLLM_URL: ""
  VLLM_API_KEY: ""
  VLLM_MAX_TOKENS: "${LIGHTSPEED_VLLM_MAX_TOKENS}"
  VLLM_TLS_VERIFY: ""
  OPENAI_API_KEY: "${OPENAI_API_KEY}"
  OPENAI_MODEL: "${OPENAI_MODEL}"
  VERTEX_AI_PROJECT: ""
  VERTEX_AI_LOCATION: ""
  GOOGLE_APPLICATION_CREDENTIALS: ""
  OLLAMA_URL: ""
  SAFETY_MODEL: ""
  SAFETY_URL: ""
  SAFETY_API_KEY: ""
