apiVersion: v1
kind: ConfigMap
metadata:
  name: lightspeed-stack
  namespace: ${RHDH_NAMESPACE}
  labels:
    app.kubernetes.io/part-of: developer-hub
data:
  lightspeed-stack.yaml: |
    name: Lightspeed Core Service (LCS)
    service:
      host: 0.0.0.0
      auth_enabled: false
      workers: 1
      color_log: true
      access_log: true
    llama_stack:
      use_as_library_client: false
      url: http://localhost:8321
    user_data_collection:
      feedback_enabled: true
      feedback_storage: "/tmp/data/feedback"
      transcripts_enabled: true
      transcripts_storage: "/tmp/data/transcripts"
    authentication:
      module: "noop"
    conversation_cache:
      type: "sqlite"
      sqlite:
        db_path: "/tmp/data/conversations/lcs_cache.db"
    mcp_servers:
      - name: mcp::backstage
        provider_id: model-context-protocol
        url: http://127.0.0.1:7007/api/mcp-actions/v1
        authorization_headers:
          Authorization: "/var/secrets/mcp/token"
