apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentId }}
  title: ${{ values.componentTitle or values.componentId }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.repoOwner }}/${{ values.repoName }}
    backstage.io/kubernetes-id: ${{ values.componentId }}
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=${{ values.componentId }}
  tags:
    - java
    - quarkus
    - react
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
